import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const REPO_ROOT = path.resolve(import.meta.dir, "..");
const PUBLIC_ROOT = path.join(REPO_ROOT, "public");
const OPTIMIZED_ROOT = path.join(PUBLIC_ROOT, "optimized");
const OUTPUT_DIRECTORY = path.join(REPO_ROOT, "src", "generated");
const DEFAULT_IMAGE_PATH = "/optimized/site/logo-86.webp";
const PRODUCT_PREFIX = "/optimized/priority-products/";
const RASTER_EXTENSIONS = new Set([
  ".avif",
  ".heic",
  ".heif",
  ".jpeg",
  ".jpg",
  ".png",
  ".webp",
]);

type GeneratedImageMetadata = {
  blurDataURL: string;
  height: number;
  width: number;
};

async function walkFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(directory, entry.name);
      return entry.isDirectory() ? walkFiles(entryPath) : [entryPath];
    }),
  );

  return files.flat();
}

function toPublicPath(filePath: string) {
  return "/" + path.relative(PUBLIC_ROOT, filePath).split(path.sep).join("/");
}

function normalizeProductKey(publicPath: string) {
  return publicPath.replace(/-\d+(?=\.[^.]+$)/, "");
}

function responsiveWidth(filePath: string) {
  const match = path.basename(filePath).match(/-(\d+)(?=\.[^.]+$)/);
  return match ? Number(match[1]) : Number.POSITIVE_INFINITY;
}

async function createPlaceholder(filePath: string) {
  const image = Bun.file(filePath).image();
  const metadata = await image.metadata();
  const placeholder = await image.placeholder();
  const placeholderBlob = await (await fetch(placeholder)).blob();

  return {
    blurDataURL: await placeholderBlob.image().webp({ quality: 20 }).dataurl(),
    height: metadata.height,
    width: metadata.width,
  } satisfies GeneratedImageMetadata;
}

async function writeGeneratedFile(fileName: string, output: string) {
  const outputPath = path.join(OUTPUT_DIRECTORY, fileName);
  let current = "";

  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    // The generated module does not exist yet.
  }

  if (current !== output) {
    await writeFile(outputPath, output);
  }
}

function renderDefaultModule(defaultPlaceholder: string) {
  return [
    "// Generated by scripts/generate-image-placeholders.ts.",
    "// Do not edit this file by hand.",
    "",
    "export const DEFAULT_IMAGE_PLACEHOLDER = " +
      JSON.stringify(defaultPlaceholder) +
      ";",
    "",
  ].join("\n");
}

function renderSiteModule(
  placeholders: Readonly<Record<string, GeneratedImageMetadata>>,
) {
  return [
    "// Generated by scripts/generate-image-placeholders.ts.",
    "// Do not edit this file by hand.",
    "",
    'import { DEFAULT_IMAGE_PLACEHOLDER } from "./default-image-placeholder";',
    "",
    "type GeneratedImageMetadata = {",
    "  blurDataURL: string;",
    "  height: number;",
    "  width: number;",
    "};",
    "",
    "const SITE_IMAGE_METADATA: Readonly<Record<string, GeneratedImageMetadata>> = " +
      JSON.stringify(placeholders, null, 2) +
      ";",
    "",
    "export function getSiteImageMetadata(src?: string | null) {",
    '  if (!src || !src.startsWith("/")) {',
    "    return undefined;",
    "  }",
    "",
    "  const pathname = src.split(/[?#]/, 1)[0];",
    "  return SITE_IMAGE_METADATA[pathname];",
    "}",
    "",
    "export function getSiteImagePlaceholder(src?: string | null) {",
    "  return getSiteImageMetadata(src)?.blurDataURL ?? DEFAULT_IMAGE_PLACEHOLDER;",
    "}",
    "",
  ].join("\n");
}

function renderProductModule(
  placeholders: Readonly<Record<string, GeneratedImageMetadata>>,
) {
  return [
    "// Generated by scripts/generate-image-placeholders.ts.",
    "// Do not edit this file by hand.",
    "",
    'import { DEFAULT_IMAGE_PLACEHOLDER } from "./default-image-placeholder";',
    "",
    "type GeneratedImageMetadata = {",
    "  blurDataURL: string;",
    "  height: number;",
    "  width: number;",
    "};",
    "",
    "const PRODUCT_IMAGE_METADATA: Readonly<Record<string, GeneratedImageMetadata>> = " +
      JSON.stringify(placeholders, null, 2) +
      ";",
    "",
    "function normalizeProductKey(src: string) {",
    "  const pathname = src.split(/[?#]/, 1)[0];",
    '  return pathname.replace(/-\\d+(?=\\.[^.]+$)/, "");',
    "}",
    "",
    "export function getProductImageMetadata(src?: string | null) {",
    '  if (!src || !src.startsWith("/")) {',
    "    return undefined;",
    "  }",
    "",
    "  return PRODUCT_IMAGE_METADATA[normalizeProductKey(src)];",
    "}",
    "",
    "export function getProductImagePlaceholder(src?: string | null) {",
    "  return (",
    "    getProductImageMetadata(src)?.blurDataURL ?? DEFAULT_IMAGE_PLACEHOLDER",
    "  );",
    "}",
    "",
  ].join("\n");
}

async function main() {
  const rasterFiles = (await walkFiles(OPTIMIZED_ROOT)).filter((filePath) =>
    RASTER_EXTENSIONS.has(path.extname(filePath).toLowerCase()),
  );
  const candidates = new Map<string, string>();

  for (const filePath of rasterFiles) {
    const publicPath = toPublicPath(filePath);
    const key = publicPath.startsWith(PRODUCT_PREFIX)
      ? normalizeProductKey(publicPath)
      : publicPath;
    const current = candidates.get(key);

    if (!current || responsiveWidth(filePath) < responsiveWidth(current)) {
      candidates.set(key, filePath);
    }
  }

  const placeholders: Record<string, GeneratedImageMetadata> = {};
  const entries = [...candidates.entries()].sort(([left], [right]) =>
    left.localeCompare(right),
  );

  for (let index = 0; index < entries.length; index += 16) {
    const batch = entries.slice(index, index + 16);
    const results = await Promise.all(
      batch.map(async ([key, filePath]) => {
        try {
          return [key, await createPlaceholder(filePath)] as const;
        } catch (error) {
          console.warn("Skipping placeholder for " + key, error);
          return null;
        }
      }),
    );

    for (const result of results) {
      if (result) placeholders[result[0]] = result[1];
    }
  }

  const defaultPlaceholder = placeholders[DEFAULT_IMAGE_PATH]?.blurDataURL;
  if (!defaultPlaceholder) {
    throw new Error(
      "Could not generate the default image placeholder from " +
        DEFAULT_IMAGE_PATH,
    );
  }

  const sitePlaceholders = Object.fromEntries(
    Object.entries(placeholders).filter(([key]) => !key.startsWith(PRODUCT_PREFIX)),
  );
  const productPlaceholders = Object.fromEntries(
    Object.entries(placeholders).filter(([key]) => key.startsWith(PRODUCT_PREFIX)),
  );

  await mkdir(OUTPUT_DIRECTORY, { recursive: true });
  await Promise.all([
    writeGeneratedFile(
      "default-image-placeholder.ts",
      renderDefaultModule(defaultPlaceholder),
    ),
    writeGeneratedFile(
      "site-image-placeholders.ts",
      renderSiteModule(sitePlaceholders),
    ),
    writeGeneratedFile(
      "product-image-placeholders.ts",
      renderProductModule(productPlaceholders),
    ),
  ]);

  console.log(
    "Generated " +
      Object.keys(sitePlaceholders).length +
      " site and " +
      Object.keys(productPlaceholders).length +
      " product image placeholders",
  );
}

await main();
